### Cria um novo usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Marie Doeaasdf",
  "email": "mariedoe@example.com",
  "senha": "123456",
  "avatar": "https://example.com/avatar.jpg",
  "papel": "EDITOR",
  "status": "ATIVO"
}

### Armazena o id do usuário
@usuarioId = 42ec656e-35a9-49c2-8d97-184101369a82

### Busca todos os usuários
GET http://localhost:3000/usuarios

### Busca um usuário pelo ID
GET http://localhost:3000/usuarios/{{usuarioId}}

### Atualiza um usuário pelo ID
PATCH http://localhost:3000/usuarios/{{usuarioId}}
Content-Type: application/json

{
  "status": "INATIVO",
  "email": "johndoe@example.com"
}

### Deleta um usuário pelo ID
DELETE http://localhost:3000/usuarios/{{usuarioId}}

### Busca paginada de usuários
GET http://localhost:3000/usuarios/query

### Gemini
POST http://localhost:3000/ai/generate
Content-Type: application/json

{
  "prompt": "Me passe 5 exercícios para treino de peitoral. Quero que me informe isso em um formato json com um campo para cada informação: nome do exercício, foco do exercício, execução, dica e se for possível um link de execução do exercício no youtube"
}